#!/bin/bash

terraform_dir=$(pwd $(dirname $0))
terraform_bin=$(type -p terraform)
if [ -z "$terraform_bin" ]; then
    echo "Could not find terraform binary in PATH.  Exiting."
    exit 1
fi
generate_mod="modules/generate"
terraform="$terraform_bin -chdir=$terraform_dir/$generate_mod"

my_args=()
while true ; do
  case "$1" in
    -var-file*|-backup*|-state*|-state-out*)
      if [[ "$1" =~ = ]] ; then
        path=${1##*=}
        arg=${1%%=$path}
        shift
      else
        arg=$1
        path=$2
        shift 2
      fi

      if [[ ! "$path" =~ ^/ ]] ; then
        path="$terraform_dir/$path"
      fi

      my_args+=($arg $path)
    ;;
    "") break ;;
    *) my_args+=($1) ; shift ;;
  esac
done

set -e
$terraform init -upgrade
$terraform apply ${my_args[@]}
