apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-utils
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "{{ .Values.platform.config_profile_path }}/dev-utils/*" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
